// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1581515135);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1581515255);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1581514895);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1581515015);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1581515375);
user_pref("browser.cache.disk.amount_written", 1);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "ZA");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 11 Feb 2020 17:19:30 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1581515136);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200110142707");
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"fac64f08-338b-4396-b88b-01395a95d39b\",\"default-theme@mozilla.org\":\"986ff35b-87b5-46db-ae76-5d366950a2a2\",\"google@search.mozilla.org\":\"eff5bb02-bcfb-4530-b476-e2da2dd8332b\",\"amazondotcom@search.mozilla.org\":\"27b19bae-87a2-46a6-bf46-9f82651b284e\",\"bing@search.mozilla.org\":\"7f5eec7f-0dd1-43c8-af4b-138961aceeb7\",\"ddg@search.mozilla.org\":\"09ed624f-9054-4f51-bb73-5d229083248c\",\"twitter@search.mozilla.org\":\"c7853bce-80a8-4a58-9843-52c5893d7cfe\",\"wikipedia@search.mozilla.org\":\"474ab951-4b92-4e43-9bf7-c46d6b2c271d\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "c1009c36-c45f-4b9d-b905-b176c1d142c");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "28fc558c-9350-4f08-bc43-30fb5857f3f4");
user_pref("services.blocklist.pinning.checked", 1581495793);
user_pref("services.settings.clock_skew_seconds", 19222);
user_pref("services.settings.last_etag", "\"1581495699019\"");
user_pref("services.settings.last_update_seconds", 1581495793);
user_pref("services.settings.main.hijack-blocklists.last_check", 1581495793);
user_pref("services.settings.main.language-dictionaries.last_check", 1581495793);
user_pref("services.settings.main.sites-classification.last_check", 1581495793);
user_pref("services.settings.security.onecrl.checked", 1581495793);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "582ddf29-48cf-4d6d-866c-3d895094b6d9");
user_pref("toolkit.telemetry.prompted", 2);
